package com.estatekit.core.enums;

public enum GateEventType {
    ENTRY_SCAN,
    EXIT_SCAN,
    EXIT_PASS_VALIDATED,
    EXIT_PASS_FAILED,
    REMOTE_APPROVAL_REQUESTED,
    REMOTE_APPROVAL_APPROVED,
    REMOTE_APPROVAL_DENIED,
    REMOTE_APPROVAL_EXPIRED,
    VISITOR_CHECK_IN,
    VISITOR_CHECK_OUT,
    VISITOR_PASS_VALIDATED,
    VISITOR_PASS_FAILED,
    VISITOR_DENIED_BLACKLIST,
    VEHICLE_DENIED_BLACKLIST,
    MANUAL_OVERRIDE_ALLOW,
    MANUAL_OVERRIDE_DENY
}
